"""Emit the plain-text title, abstract and keywords the submission form asks for.

    python paper/make_portal_fields.py    # -> paper/build/portal_fields.txt

The portal keeps its own copy of the front matter, typed into a web page. On the
companion submission that copy went three weeks out of date without anything noticing,
and it is the half an editor reads first. A copy that is generated cannot drift.

Markdown emphasis, code spans and citation numbers are stripped, because the field takes
plain text, renders none of it, and carries no reference list for a bracketed number to
point at.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PAPER = Path(__file__).resolve().parent
sys.path.insert(0, str(PAPER))

import build_manuscript  # noqa: E402
import presubmission_check  # noqa: E402

BUILT = build_manuscript.DEFAULT_OUTPUT
OUT = PAPER / "build" / "portal_fields.txt"

#: What the form enforces. Taken from the check rather than restated, so there is one
#: place that knows the journal's limit.
ABSTRACT_WORDS = presubmission_check.ABSTRACT_WORDS


def plain(text: str) -> str:
    """Markdown down to what a plain-text field can carry."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text, flags=re.S)
    text = re.sub(r"\*(.+?)\*", r"\1", text, flags=re.S)
    text = re.sub(r"`(.+?)`", r"\1", text, flags=re.S)
    text = re.sub(r" ?\[\d+(?:\s*,\s*\d+)*\]", "", text)
    return re.sub(r"[ \t]+", " ", text).strip()


def fields() -> dict[str, str]:
    body = re.sub(r"<!--.*?-->", "", BUILT.read_text(encoding="utf-8"), flags=re.S)
    title = plain(next(line[2:] for line in body.splitlines() if line.startswith("# ")))
    abstract = plain(body.split("## Abstract")[1].split("**Keywords")[0])
    abstract = "\n\n".join(
        " ".join(paragraph.split())
        for paragraph in abstract.split("\n\n")
        if paragraph.strip()
    )
    keywords = plain(body.split("**Keywords:**")[1].split("\n\n")[0])
    return {"title": title, "abstract": abstract, "keywords": keywords}


def main(argv: list[str] | None = None) -> int:
    if not BUILT.exists():
        print("build/manuscript.md is missing; run paper/build_manuscript.py first")
        return 2
    parts = fields()
    words = len(parts["abstract"].split())

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"=== TITLE ({len(parts['title'])} characters) ===\n{parts['title']}\n\n"
        f"=== ABSTRACT ({words} / {ABSTRACT_WORDS} words) ===\n{parts['abstract']}\n\n"
        f"=== KEYWORDS ===\n{parts['keywords']}\n\n"
        "Generated by paper/make_portal_fields.py from build/manuscript.md. Do not\n"
        "edit by hand: a form's copy of the front matter has gone stale before.\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")
    print(f"  title {len(parts['title'])} characters")
    print(f"  abstract {words}/{ABSTRACT_WORDS} words")
    if words > ABSTRACT_WORDS:
        print("  OVER THE LIMIT")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
